FROM python:3.11-alpine as builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev

COPY pyproject.toml /app/

RUN pip install --upgrade pip && \
pip install --no-cache-dir --prefix=/install . pytest

FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /install /usr/local
COPY src /app/src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8063"]
