name: Deploy

on:
push:
branches: [ "master" ]

jobs:
build:
runs-on: self-hosted
outputs:
image_tag: ${{ steps.meta.outputs.tags }}
steps:
- name: Checkout code
uses: actions/checkout@v4

- name: Docker metadata
id: meta
uses: docker/metadata-action@v5
with:
images: ${{ vars.DOCKERHUB_USERNAME }}/python-crud
tags: |
type=sha

- name: Setup Docker Buildx
uses: docker/setup-buildx-action@v3

- name: Login to Docker Hub
uses: docker/login-action@v3
with:
username: ${{ vars.DOCKERHUB_USERNAME }}
password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: Build and push
uses: docker/build-push-action@v3
with:
context: .
file: ./Dockerfile.prod
push: true
tags: ${{ steps.meta.outputs.tags }}

test:
needs: build
runs-on: self-hosted
env:
DATABASE_URL: postgresql+psycopg://kubsu:kubsu@127.0.0.1:5432/kubsu
services:
postgres:
image: postgres:15-alpine
ports:
- "5432:5432"
env:
POSTGRES_DB: kubsu
POSTGRES_USER: kubsu
POSTGRES_PASSWORD: kubsu
options: >-
--health-cmd pg_isready
--health-interval 10s
--health-timeout 5s
--health-retries 5

steps:
- name: Pull image
run: docker pull ${{ needs.build.outputs.image_tag }}

- name: Run tests
run: docker run --rm --network=host \
-e DATABASE_URL=${DATABASE_URL} \
${{ needs.build.outputs.image_tag }}

deploy:
needs: test
runs-on: self-hosted

steps:
- name: Deploy to on server
uses: appleboy/ssh-action@v1
with:
host: ${{ secrets.SSH_HOST }}
port: ${{ secrets.SSH_PORT }}
username: ${{ secrets.SSH_USERNAME }}
key: ${{ secrets.SSH_PRIVATE_KEY }}
script: |
podman login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

IMAGE_TAG="${{ needs.build.outputs.image_tag }}"

podman stop python-crud || true
podman rm python-crud || true
podman rmi $IMAGE_TAG || true
podman pull $IMAGE_TAG

podman run -d \
--name python-crud \
--network host \
-e DATABASE_URL=postgresql+psycopg://kubsu:kubsu@127.0.0.1:5432/kubsu \
$IMAGE_TAG

echo "Container has been deployed successfully!"
